---
title: "page2"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
library(palmerpenguins) #install.packages("palmerpenguins")
library(tidyverse)
```


## Data
```{r}
dim(penguins)
```
```{r}
colnames(penguins)
```
## Single trait distribution
```{r, message=FALSE}
penguins %>%
  ggplot(mapping = aes(x = bill_length_mm, fill=species)) +
  geom_boxplot(outlier.colour="black", outlier.shape=16,
             outlier.size=2, notch=FALSE)
```



```{r, message=FALSE}
filter(penguins, !is.na(species)) %>%
  ggplot() +
  geom_density(mapping = aes(x = bill_length_mm, fill=species), alpha=0.5)
```



## Relationship between multiple traits
```{r, message=FALSE}
penguins %>%
  ggplot(mapping = aes(x = body_mass_g, y=flipper_length_mm, color=species)) +
  geom_point() +
  geom_smooth(method="lm")
```
  
## Sexual dimorphism
```{r, message=FALSE}
penguins %>%
  ggplot(mapping = aes(x = bill_length_mm, y=bill_depth_mm, color=sex)) +
  geom_point(size=1) +
  facet_wrap(~species)
```

```{r, message=FALSE}
penguins %>%
  ggplot(mapping = aes(x=flipper_length_mm, y=sex, color=sex)) +
  geom_boxplot(outlier.alpha = 0, alpha=0) +
  geom_jitter(width = 0, size=1) +
  coord_flip() +
  facet_wrap(~species)
```
